on: [push]

name: tnfsd Build

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build tnfsd
        run: cd D:\a\tnfsd\tnfsd\src && make OS=Windows_NT DEBUG=yes USAGELOG=yes
      - uses: actions/upload-artifact@master
        with:
          name: tnfsd_win-x64
          path: bin/tnfsd.exe

  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build tnfsd
        run: cd /home/runner/work/tnfsd/tnfsd/src && make OS=LINUX DEBUG=yes USAGELOG=yes
      - uses: actions/upload-artifact@master
        with:
          name: tnfsd_linux-x64
          path: bin/tnfsd

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build tnfsd
        run: cd /Users/runner/work/tnfsd/tnfsd/src && make OS=BSD DEBUG=yes USAGELOG=yes
      - uses: actions/upload-artifact@master
        with:
          name: tnfsd_macos-arm64
          path: bin/tnfsd

  build-macos-x64:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build tnfsd
        run: cd /Users/runner/work/tnfsd/tnfsd/src && make OS=BSD DEBUG=yes USAGELOG=yes
      - uses: actions/upload-artifact@master
        with:
          name: tnfsd_macos-x64
          path: bin/tnfsd
